// for of
var fruits = ["mango","apple","pineapple","orange","banana"];
for (var x of fruits) {
    console.log(x);
}


// for in 
var cars = ["BMW","AUDI","BENS","MARUTHI","HYUDAI"];
for (var I in cars) {
    console.log(I);
}

// for 
var arr = [1,2,3,4,5,6,7,8,9]
for (i=0; i<arr.length;i++){
    console.log(arr);
}


// javascript resume 
var Avinashobj = {
    "name" : "Avinash",
    "age" :"24",
    "Height" : "174cm",
    "Weight" : "76kg",
    "Education" : "master's in Structural Engineering",
    "Work Experience" : "2 years",
    };{
    console.log(Avinashobj);
    }
    